---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  conection: ssh
  ignore_erros: false
  tasks:
    - name: Task Name Here
      ping:
    - name: Install telnet
      package:
        name: 
          - telnet
          - elinks
          - wget
          -unzip
        state: present  