---
- name: loop
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: loop
      package:
        name: "{{item}}"
        state: present
    with_items:
      - httpd
      - talnet
      - lftp
      - unzip
      - wget

    - name: command
      commond: "{{item}}"
      with_items:
       - "yum install talnet -y"
       - "free -m"
       - "w"