---
- name: conditional Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  task: 
     -name: install on centos 6 only
     when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
     package:
       name: kernel
       state: latest 
   
  
      -name: restart
     when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
     shell: "/sbin/shutdown -r now"
       
    